{dede:noteinfo notename="https://www.baidu.com/s?wd=navicat%20premium%E6%BF%80%E6%B4%BB&rsv_spt=1&rsv_iqid=0xda4c8fb900010abe&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=1&rsv_dl=ib&rsv_n=1&rsv_sug3=1&rsv_sug1=1&rsv_sug7=100&rsv_t=6c43L2zglazu%2BlX9XPVCqW5wX%2BiI0Yv%2FoOEOsG0wj2KMjyxoroMESfUGx5KCHNtqtTKd&sug=navicat%2520premium%25E6%25BF%2580%25E6%25B4%25BB" channelid="1" macthtype="string"
refurl="http://" sourcelang="gb2312" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="hand" rssurl="http://" regxurl="https://www.baidu.com/s?wd=navicat%20premium%E6%BF%80%E6%B4%BB&rsv_spt=1&rsv_iqid=0xda4c8fb900010abe&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=1&rsv_dl=ib&rsv_n=1&rsv_sug3=1&rsv_sug1=1&rsv_sug7=100&rsv_t=6c43L2zglazu%2BlX9XPVCqW5wX%2BiI0Yv%2FoOEOsG0wj2KMjyxoroMESfUGx5KCHNtqtTKd&sug=navicat%2520premium%25E6%25BF%2580%25E6%25B4%25BB"
startid="1" endid="" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
    {dede:addurls}https://www.baidu.com/s?wd=navicat%20premium%E6%BF%80%E6%B4%BB&rsv_spt=1&rsv_iqid=0xda4c8fb900010abe&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=1&rsv_dl=ib&rsv_n=1&rsv_sug3=1&rsv_sug1=1&rsv_sug7=100&rsv_t=6c43L2zglazu%2BlX9XPVCqW5wX%2BiI0Yv%2FoOEOsG0wj2KMjyxoroMESfUGx5KCHNtqtTKd&sug=navicat%2520premium%25E6%25BF%2580%25E6%25B4%25BB{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="yuRUbf">{/dede:areastart}
    {dede:areaend}</div>{/dede:areaend}
{/dede:listrule}
