<?php
$z[0]=Array("noteinfo","",0,224);
$z[0][4]=array();
$z[0][4]['notename']="搜狗";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="https://english.sogou.com/english?query=bearing&b_o_e=1&ie=utf8&fr=common_nav";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}https://english.sogou.com/english?query=bearing&b_o_e=1&ie=utf8&fr=common_nav{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<div id=\"main\" class=\"main\">{/dede:areastart}\r\n    {dede:areaend}</div>{/dede:areaend}\r\n",228,773);
$z[1][4]=array();
$z[1][4]['sourcetype']="hand";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="https://english.sogou.com/english?query=bearing&b_o_e=1&ie=utf8&fr=common_nav";
$z[1][4]['startid']="1";
$z[1][4]['endid']="";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="0";
$z[1][4]['usemore']="0";

?>