{dede:noteinfo notename="ceshi" channelid="1" macthtype="string"
refurl="http://" sourcelang="gb2312" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://bearingsize.info/catalogue-online/deep-groove-ball-bearings.html?p=(*)"
startid="1" endid="1309" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div id="cont_txt" style="height: auto !important;">{/dede:areastart}
    {dede:areaend}</div>{/dede:areaend}
{/dede:listrule}
