<?php
$z[0]=Array("addurls","https://en.wikipedia.org/wiki/Bearing_(angle)",6,80);
$z[0][4]=array();
$z[1]=Array("batchrule","",86,119);
$z[1][4]=array();
$z[2]=Array("regxrule","",125,156);
$z[2][4]=array();
$z[3]=Array("areastart","<div id=\"toc\" class=\"toc\" role=\"navigation\" aria-labelledby=\"mw-toc-heading\">",162,272);
$z[3][4]=array();
$z[4]=Array("areaend","</div>",278,313);
$z[4][4]=array();

?>