{dede:noteinfo notename="" channelid="1" macthtype="string"
refurl="http://" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://bearingsize.info/catalogue-online.html?p=(*)"
startid="1" endid="7416" addv="1" urlrule="area"
 musthas="" nothas="" listpic="0" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div id="content">{/dede:areastart}
    {dede:areaend}</div>{/dede:areaend}
{/dede:listrule}
