<?php
$z[0]=Array("addurls","https://www.google.com/search?source=hp&ei=l6o8YMKuI8qGsQWN16Vg&iflsig=AINFCbYAAAAAYDy4p6aX7UR0XACXmdojMmBA5y-_h1Q5&q=bearing&oq=bearing&gs_lcp=Cgdnd3Mtd2l6EAMyAggAMgIIADICCAAyAggAUJQZWLsmYJsoaAJwAHgAgAGHAogBggySAQMyLTaYAQCgAQGqAQdnd3Mtd2l6sAEA&sclient=gws-wiz&ved=0ahUKEwiC1p2Q247vAhVKQ6wKHY1rCQwQ4dUDCAc&uact=5",6,347);
$z[0][4]=array();
$z[1]=Array("batchrule","",353,386);
$z[1][4]=array();
$z[2]=Array("regxrule","",392,423);
$z[2][4]=array();
$z[3]=Array("areastart","<div class=\"g\">",429,477);
$z[3][4]=array();
$z[4]=Array("areaend","</div>",483,518);
$z[4][4]=array();

?>