
    {dede:addurls}https://www.google.com/search?source=hp&ei=l6o8YMKuI8qGsQWN16Vg&iflsig=AINFCbYAAAAAYDy4p6aX7UR0XACXmdojMmBA5y-_h1Q5&q=bearing&oq=bearing&gs_lcp=Cgdnd3Mtd2l6EAMyAggAMgIIADICCAAyAggAUJQZWLsmYJsoaAJwAHgAgAGHAogBggySAQMyLTaYAQCgAQGqAQdnd3Mtd2l6sAEA&sclient=gws-wiz&ved=0ahUKEwiC1p2Q247vAhVKQ6wKHY1rCQwQ4dUDCAc&uact=5{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="g">{/dede:areastart}
    {dede:areaend}</div>{/dede:areaend}
