{dede:noteinfo notename="skf" channelid="1" macthtype="string"
refurl="http://" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="https://www.fagbearing.cc/SKF-bearings/list_35_(*).html"
startid="1" endid="136" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="prolist">{/dede:areastart}
    {dede:areaend}</div>{/dede:areaend}
{/dede:listrule}
