{dede:noteinfo notename="skf" channelid="1" macthtype="string"
    refurl="https://www.dksbearing.com/products/skf/SKF-24022-CC-C4W33.html" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="https://www.dksbearing.com/products/skf/index_(*).html"
startid="2" endid="35" addv="1" urlrule="area" musthas=""
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}https://www.dksbearing.com/products/skf/index.html{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="product_show">{/dede:areastart}
    {dede:areaend}</div>{/dede:areaend}
{/dede:listrule}
