{dede:noteinfo notename="测试" channelid="1" macthtype="string"
refurl="http://bearingsize.info/catalogue-online/thrust-ball-bearings/bearing-0-5-fbj-obj78974.html" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://bearingsize.info/catalogue-online.html?p=(*)"
startid="1" endid="7416" addv="1" urlrule="area"
 musthas="" nothas="" listpic="0" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<p>{/dede:areastart}
    {dede:areaend}</p>{/dede:areaend}
{/dede:listrule}
