<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	

<field:Original itemname="原版的" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:Original>

<field:Type itemname="类型" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:Type>

<field:Item itemname="物品" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:Item>

<field:Inner itemname="内" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:Inner>

<field:Outner itemname="外层" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:Outner>

<field:Thickness itemname="厚度" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:Thickness>

<field:Weight itemname="重量" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:Weight>

<field:brand itemname="品牌" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:brand>

<field:internal itemname="内径" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:internal>

<field:suoluetu itemname="缩略图" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:suoluetu>

<field:bodyself itemname="正文" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:bodyself>

