{dede:noteinfo notename="搜狗" channelid="1" macthtype="string"
refurl="https://english.sogou.com/english?query=bearing&b_o_e=1&ie=utf8&fr=common_nav" sourcelang="gb2312" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="hand" rssurl="http://" regxurl="https://english.sogou.com/english?query=bearing&b_o_e=1&ie=utf8&fr=common_nav"
startid="1" endid="" addv="1" urlrule="area"
 musthas="" nothas="" listpic="0" usemore="0"}
    {dede:addurls}https://english.sogou.com/english?query=bearing&b_o_e=1&ie=utf8&fr=common_nav{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div id="main" class="main">{/dede:areastart}
    {dede:areaend}</div>{/dede:areaend}
{/dede:listrule}
