<?php
$z[0]=Array("noteinfo","",0,504);
$z[0][4]=array();
$z[0][4]['notename']="https://www.baidu.com/s?wd=navicat%20premium%E6%BF%80%E6%B4%BB&rsv_spt=1&rsv_iqid=0xda4c8fb900010abe&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=1&rsv_dl=ib&rsv_n=1&rsv_sug3=1&rsv_sug1=1&rsv_sug7=100&rsv_t=6c43L2zglazu%2BlX9XPVCqW5wX%2BiI0Yv%2FoOEOsG0wj2KMjyxoroMESfUGx5KCHNtqtTKd&sug=navicat%2520premium%25E6%25BF%2580%25E6%25B4%25BB";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://";
$z[0][4]['sourcelang']="gb2312";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}https://www.baidu.com/s?wd=navicat%20premium%E6%BF%80%E6%B4%BB&rsv_spt=1&rsv_iqid=0xda4c8fb900010abe&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=1&rsv_dl=ib&rsv_n=1&rsv_sug3=1&rsv_sug1=1&rsv_sug7=100&rsv_t=6c43L2zglazu%2BlX9XPVCqW5wX%2BiI0Yv%2FoOEOsG0wj2KMjyxoroMESfUGx5KCHNtqtTKd&sug=navicat%2520premium%25E6%25BF%2580%25E6%25B4%25BB{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<div class=\"g\">{/dede:areastart}\r\n    {dede:areaend}</div>{/dede:areaend}\r\n",508,1596);
$z[1][4]=array();
$z[1][4]['sourcetype']="hand";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="https://www.baidu.com/s?wd=navicat%20premium%E6%BF%80%E6%B4%BB&rsv_spt=1&rsv_iqid=0xda4c8fb900010abe&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=1&rsv_dl=ib&rsv_n=1&rsv_sug3=1&rsv_sug1=1&rsv_sug7=100&rsv_t=6c43L2zglazu%2BlX9XPVCqW5wX%2BiI0Yv%2FoOEOsG0wj2KMjyxoroMESfUGx5KCHNtqtTKd&sug=navicat%2520premium%25E6%25BF%2580%25E6%25B4%25BB";
$z[1][4]['startid']="1";
$z[1][4]['endid']="";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>