<?php
$z[0]=Array("name","\r\n",1,129);
$z[0][4]=array();
$z[0][4]['itemname']="name";
$z[0][4]['autofield']="1";
$z[0][4]['type']="text";
$z[0][4]['isnull']="true";
$z[0][4]['default']="your name";
$z[0][4]['maxlength']="250";
$z[0][4]['page']="";
$z[1]=Array("email","\r\n",132,264);
$z[1][4]=array();
$z[1][4]['itemname']="Email";
$z[1][4]['autofield']="1";
$z[1][4]['type']="text";
$z[1][4]['isnull']="true";
$z[1][4]['default']="xxx@xx.com";
$z[1][4]['maxlength']="250";
$z[1][4]['page']="";
$z[2]=Array("address","\r\n",267,407);
$z[2][4]=array();
$z[2][4]['itemname']="Address";
$z[2][4]['autofield']="1";
$z[2][4]['type']="text";
$z[2][4]['isnull']="true";
$z[2][4]['default']="your address";
$z[2][4]['maxlength']="250";
$z[2][4]['page']="";

?>