<?php
$z[0]=Array("noteinfo","",0,151);
$z[0][4]=array();
$z[0][4]['notename']="fag";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<div class=\"listing-wrapper\">{/dede:areastart}\r\n    {dede:areaend}</div>{/dede:areaend}\r\n",155,622);
$z[1][4]=array();
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="https://www.qualitybearingsonline.com/fag?sort=bestselling&page=(*)";
$z[1][4]['startid']="1";
$z[1][4]['endid']="7416";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="fag";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>