{dede:noteinfo notename="fag" channelid="1" macthtype="string"
refurl="http://" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="https://www.qualitybearingsonline.com/fag?sort=bestselling&page=(*)"
startid="1" endid="7416" addv="1" urlrule="area"
 musthas="fag" nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="listing-wrapper">{/dede:areastart}
    {dede:areaend}</div>{/dede:areaend}
{/dede:listrule}
