<?php
$z[0]=Array("noteinfo","",0,154);
$z[0][4]=array();
$z[0][4]['notename']="ceshi";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://";
$z[0][4]['sourcelang']="gb2312";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}https://en.wikipedia.org/wiki/Bearing_(angle){/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<div id=\"toc\" class=\"toc\" role=\"navigation\" aria-labelledby=\"mw-toc-heading\">{/dede:areastart}\r\n    {dede:areaend}</div>{/dede:areaend}\r\n",158,724);
$z[1][4]=array();
$z[1][4]['sourcetype']="hand";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://bearingsize.info/catalogue-online/deep-groove-ball-bearings.html?p=(*)";
$z[1][4]['startid']="1";
$z[1][4]['endid']="1309";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>