<?php
$z[0]=Array("addurls","https://www.baidu.com/s?wd=navicat%20premium%E6%BF%80%E6%B4%BB&rsv_spt=1&rsv_iqid=0xda4c8fb900010abe&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=1&rsv_dl=ib&rsv_n=1&rsv_sug3=1&rsv_sug1=1&rsv_sug7=100&rsv_t=6c43L2zglazu%2BlX9XPVCqW5wX%2BiI0Yv%2FoOEOsG0wj2KMjyxoroMESfUGx5KCHNtqtTKd&sug=navicat%2520premium%25E6%25BF%2580%25E6%25B4%25BB",6,390);
$z[0][4]=array();
$z[1]=Array("batchrule","",396,429);
$z[1][4]=array();
$z[2]=Array("regxrule","",435,466);
$z[2][4]=array();
$z[3]=Array("areastart","<div class=\"g\">",472,520);
$z[3][4]=array();
$z[4]=Array("areaend","</div>",526,561);
$z[4][4]=array();

?>