<?php
$z[0]=Array("include","",0,37);
$z[0][4]=array();
$z[0][4]['filename']="header.htm";
$z[1]=Array("channel","\r\n            <div class=\"col-md-6 gal-sec mt-50\">\r\n                <div class=\"gallery-grid1\">\r\n                    <a title=\"Attractive home purchase offers.\" href=\"[field:typeurl/]\">\r\n                        <img src=\"/images/g1.jpg\" alt=\" \" class=\"img-responsive\" />\r\n                        <div class=\"p-mask\">\r\n                            <h4>[field:typename/]</h4>\r\n                            <p>Brand</p>\r\n                        </div>\r\n                    </a>\r\n                </div>\r\n            </div>\r\n            ",520,1091);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[2]=Array("include","",1717,1754);
$z[2][4]=array();
$z[2][4]['filename']="footer.htm";

?>