<?php
$z[0]=Array("channel","\r\n <li class=\"nav-item mr-3\"><a class=\"nav-link\" href=\"[field:typelink /]\">[field:typename/]</a></li>\r\n    ",2226,2487);
$z[0][4]=array();
$z[0][4]['type']="top";
$z[0][4]['row']="7";
$z[0][4]['currentstyle']="<li class='nav-item mr-3 active'><a class='nav-link' href='~typelink~'>~typename~</a></li>";
$z[1]=Array("global","",2653,2681);
$z[1][4]=array();
$z[1][4]['name']="cfg_sendemail";

?>