<?php
$z[0]=Array("channel","\r\n <li class=\"nav-item mr-3\"><a class=\"nav-link\" href=\"[field:typelink /]\">[field:typename/]</a></li>\r\n    ",2527,2788);
$z[0][4]=array();
$z[0][4]['type']="top";
$z[0][4]['row']="7";
$z[0][4]['currentstyle']="<li class='nav-item mr-3 active'><a class='nav-link' href='~typelink~'>~typename~</a></li>";
$z[1]=Array("global","",3123,3151);
$z[1][4]=array();
$z[1][4]['name']="cfg_sendemail";
$z[2]=Array("global","",16188,16216);
$z[2][4]=array();
$z[2][4]['name']="cfg_sendemail";
$z[3]=Array("include","",17457,17494);
$z[3][4]=array();
$z[3][4]['filename']="footer.htm";

?>