<?php
$z[0]=Array("include","",0,37);
$z[0][4]=array();
$z[0][4]['filename']="header.htm";
$z[1]=Array("list","\r\n            <div class=\"col-md-6 gal-sec mt-50\">\r\n                <div class=\"gallery-grid1\">\r\n                    <a title=\"Attractive home purchase offers.\" href=\"[field:arcurl/]\">\r\n                        <img src=\"[field:picname/]\" alt=\" \" class=\"img-responsive\" />\r\n                        <div class=\"p-mask\">\r\n                            <h4>[field:title/]</h4>\r\n                            <p>[field:infos/]...</p>\r\n                        </div>\r\n                    </a>\r\n                </div>\r\n            </div>\r\n            ",521,1125);
$z[1][4]=array();
$z[1][4]['pagesize']="11";
$z[1][4]['titlelen']="99";
$z[1][4]['infolen']="50";
$z[2]=Array("pagelist","",1259,1337);
$z[2][4]=array();
$z[2][4]['listitem']="index,end,pre,next,pageno";
$z[2][4]['listsize']="3";
$z[2][4]['pagelang']="";
$z[3]=Array("global","",2865,2893);
$z[3][4]=array();
$z[3][4]['name']="cfg_sendemail";
$z[4]=Array("include","",2976,3013);
$z[4][4]=array();
$z[4][4]['filename']="footer.htm";

?>